### ISSUE TITLE
Integrate exarl/state.py into DQN for continuous action space

### ISSUE THREAD

**Issue by cmahrens** [exalearn/EXARL#186]
Integrate the state class into DQN for continuous action space to discretize it so we can run DQN on continuous environments and possibly compare to DDPG.

**Comment by aik7** [comment]
I updated the `exarl/utils/action.py` file in the develop branch with some instructions.  I need to add `try...catch` later.  The instruction is included in the file.

```
# How to use this class
  # Set the class with the following three required arrays
    action = Action(
        arrLower=arrLower,            # an arry containing lower value for each dimension
        arrUpper=arrUpper,            # an arry containing upper value for each dimension
        arrNumClasses=arrNumClasses)  # an arry containing # of disretized classes in each dimension
  # Convert the continuous valued array (arrContAction) to its discretized array (arrDiscAction)
  # using discrete uniform distribution
    arrDiscAction = action.descretize(arrContAction)
```

**Comment by jmohdyusof** [comment]
Please reformat the comments to match the numpy docstring format

**Comment by aik7** [comment]
Is [this](https://www.python.org/dev/peps/pep-0008/#comments)  what I should follow?

**Comment by jmohdyusof** [comment]
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

**Comment by aik7** [comment]
Thanks.  Btw, there should be review process in the workflow between in-process and done.

**Comment by jmohdyusof** [comment]
That would make sense, but I don't have control over anything in this repo

**Comment by rvinaybharadwaj** [comment]
I can make the `develop` branch protected and force a review.

**Comment by jmohdyusof** [comment]
I don't think you want to protect develop, but issues should be reviewed, not just closed without any chance to provide feedback

**Comment by aik7** [comment]
Sorry for closing this issue.  I usually assign someone to review, and move to review in the workflow.  Who should I assign to review?

I reformatted the comments to match [the numpy docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html), and used `autopep8`.

**Comment by jmohdyusof** [comment]
Push to develop, so that I can pull it and check if the docstrings work

**Comment by jmohdyusof** [comment]
The function documentation looks good, but the description is weirdly formatted, and probably somewhat redundant? 
![image](https://user-images.githubusercontent.com/732447/151250917-ecbf52ad-9a31-4821-9da0-2ea75dfc465d.png)

**Comment by aik7** [comment]
I removed the redundancy in the example, and pushed the file to the develop branch.

**Comment by jmohdyusof** [comment]
The formatting was still off (indentation matters) but i fixed it along with a few typos.

**Comment by aik7** [comment]
I did not get any info after using autopep8.  Anyway, thanks!

**Comment by jmohdyusof** [comment]
Autopep8 doesn't check spelling, and cannot check contents of comments/docstrings anyway AFAIK

**Comment by aik7** [comment]
Thanks, I thought autopep8 checks the indentation of comments.

**Comment by jmohdyusof** [comment]
Comments and docstrings are totally different. Docstrings have their own syntax, and the indentation is not wrong, it is just not doing what you thing it is. Adding indentation makes a new paragraph, separate from the previous line.
