### ISSUE TITLE
Problem with CahnHilliardEnv

### ISSUE THREAD

**Issue by hellofinch** [exalearn/EXARL#227]
I want to try the CahnHilliardEnv but I see [`ch2d` imported](https://github.com/exalearn/EXARL/blob/develop/exarl/envs/env_vault/ExaCH.py#L19). I try to install the package using the command `pip install ch2d` but failed.

Where can I find that package? I search `CahnHilliard2D` on the Github and there are so many codes. It confused me.

**Comment by rvinaybharadwaj** [comment]
Refer to .gitmodules in https://github.com/exalearn/EXARL/commit/043293b63d5d755186b0fb3027e1cad97ceb1696

**Comment by fc524079318** [comment]
I got the package and try to compile it,but I met an error when I use the Makefile ,it said configure does not support Python 3 yet,please run as python2 'CahnHilliard2D/cpp/external/petsc/configure'    
[external/CMakeFiles/petsc_external.dir/build.make:92:external/petsc_external-prefix/src/petsc_external-stamp/petsc_external-configure] Error 1

Could you please tell me how to solve this error?

**Comment by fc524079318** [comment]
> Refer to .gitmodules in [043293b](https://github.com/exalearn/EXARL/commit/043293b63d5d755186b0fb3027e1cad97ceb1696)

I got the package and try to compile it,but I met an error when I use the Makefile ,it said configure does not support Python 3 yet,please run as python2 'CahnHilliard2D/cpp/external/petsc/configure'
[external/CMakeFiles/petsc_external.dir/build.make:92:external/petsc_external-prefix/src/petsc_external-stamp/petsc_external-configure] Error 1

Could you please tell me how to solve this error?

**Comment by hellofinch** [comment]
Thanks! It's solved.
