### ISSUE TITLE
Problem with sync_learner.py on develop branch

### ISSUE THREAD

**Issue by fc524079318** [exalearn/EXARL#228]
I try to use develop branch  and the async workflow to run ExaCartPoleStatic but I met an error at exarl/workflow/workflow_vault/sync_leaner.py  line 244 in write_log.   I see the code use the attribute "nepisodes" but it is undefined in this function.
How can I run the program correctly？

**Comment by rvinaybharadwaj** [comment]
Can you paste the error?

**Comment by fc524079318** [comment]
File "start.py", line 24, in <module>
    exa_learner.run()
  File "/home/ai/fc/EXARL/exarl/base/learner_base.py", line 113, in run
    self.workflow.run(self)
  File "/home/ai/fc/EXARL/exarl/workflows/workflow_vault/async_learner.py", line 147, in run
    keep_running = self.actor(workflow, nepisodes)
  File "/home/ai/fc/EXARL/exarl/workflows/workflow_vault/sync_learner.py", line 571, in actor
    self.write_log(self.current_state, action, reward, next_state, self.total_reward, self.done, episode, self.steps, policy_type, epsilon)
  File "/home/ai/fc/EXARL/exarl/workflows/workflow_vault/sync_learner.py", line 244, in write_log
    if (episode == (self.nepisodes - 1)) or (episode + 1 % self.log_frequency == 0):
AttributeError: 'ASYNC' object has no attribute 'nepisodes'

**Comment by rvinaybharadwaj** [comment]
What command did you run?

**Comment by fc524079318** [comment]
I run the command listed in the part running EXARL using MPI  in READMEmd,like
```
from mpi4py import MPI
import exarl.utils.analyze_reward as ar
import time
import exarl as erl
import mpi4py.rc
mpi4py.rc.threads = False
mpi4py.rc.recv_mprobe = False

# MPI communicator
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

# Get run parameters using CANDLE
# run_params = initialize_parameters()

# Create learner object and run
exa_learner = erl.ExaLearner(comm)

# Run the learner, measure time
start = time.time()
exa_learner.run()
elapse = time.time() - start

# Compute and print average time
max_elapse = comm.reduce(elapse, op=MPI.MAX, root=0)
elapse = comm.reduce(elapse, op=MPI.SUM, root=0)

if rank == 0:
    print("Average elapsed time = ", elapse / size)
    print("Maximum elapsed time = ", max_elapse)
    # Save rewards vs. episodes plot
    ar.save_reward_plot()
```

**Comment by fc524079318** [comment]
I use mpiexec -np 4 python start.py to run it with learner_cfg.json like
{
    "agent": "DQN-v0",
    "env": "ExaCartPoleStatic-v0",
    "workflow": "async",
    "n_episodes": 10,
    "n_steps": 10,
    "model": "MLP",
    "output_dir": "./results_dir/",
    "process_per_env": 1,
    "log_level": [3, 3],
    "log_frequency": 1,
    "profile": "None"
}
