### ISSUE TITLE
Setting OpenMP threads for multicore environments

### ISSUE THREAD

**Issue by sg0** [exalearn/EXARL#42]
Currently, users need to pass OpenMP threads explicitly in ExaRL. The default value of the number of threads in OpenMP parallel region is set in ExaRL, and not taken from the OMP_NUM_THREADS environment variable. A user may set OMP_NUM_THREADS at a higher level (like in a job script) and expect an ExaRL environment to use that many threads, forgetting to set the OpenMP thread parameter in ExaRL config. 

Therefore, we need to make a decision about the default number of threads, two options:
1. Read the OMP_NUM_THREADS environment variable and treat it as the default.
2. Ignore OMP_NUM_THREADS and require users to explicitly pass the number of threads.

**Comment by rvinaybharadwaj** [comment]
This can be an env level config
